### PR TITLE
feat: add node affinity + no schedule on fargate

### PR DESCRIPTION
**Pull request by vramahandry**
*Description of changes:*

Add node affinity + no schedule on fargate

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jjkr** [comment]
Thank you for the contribution. The changes look good. We're cutting a release right now then will merge this after 1.5.1 is out.

**Comment by vramahandry** [comment]
@jjkr Do I need to rebase from main because the build doesn't passed

**Comment by jjkr** [comment]
We have an issue right now with integration tests running on external PRs. They pass so I merged. Thank you for the contribution!

**Comment by vramahandry** [comment]
Hello @jjkr do you know when you will release the new helm chart with this default values ?

**Pull request merged**
